# Kya Allen - HW 10 - Technique for Order of Preference by Similarity to Ideal Solution

In [1]:
import numpy as np
import pandas as pd

In [22]:
Averaged_df = pd.read_csv('AveragedData.csv')
Averaged_df = Averaged_df.set_index('Monitoring station')
Averaged_df

O(3)        CO      NO(2)     SO(2)  \
Monitoring station                                                     
National Housing Authority  19.170733  0.752367  20.566133  5.635600   
Huai Khwang                 13.638900  0.899567  33.505133  5.447333   
Nonsee Vitaya school        12.516167  0.678600  29.113000  6.356300   
Singharatpitayakom school   17.999433  0.853233  20.193200  5.454400   
Thonburi                    14.644600  1.115833  27.371733  7.125900   
Traffic Police Residence    12.162667  1.201933  33.243500  7.131267   
Dlndaenq                     6.288967  1.744833  45.939600  7.472333   

                                PM-10  
Monitoring station                     
National Housing Authority  45.220433  
Huai Khwang                 50.759933  
Nonsee Vitaya school        61.836867  
Singharatpitayakom school   59.533167  
Thonburi                    55.399267  
Traffic Police Residence    47.035100  
Dlndaenq                    56.077767

## The above dataframe is from a CSV of the 3 year averages for each data point, computed in Google Sheets. Now We'll Normalize the vectors with L1 (Manhattan) and L2 (Euclidean) norms to make sure the scale of all the data is comparable for distance based metrics.

### L2 (Euclidean) Norm - values divided by the square root of the sum of the squared values

In [55]:

AveragedMatrix = np.array(Averaged_df)
AveragedMatrix = AveragedMatrix.T

for i in range(0, 5):
    AveragedMatrix[i] = np.sqrt(np.sum(np.square(AveragedMatrix[i])))
AveragedMatrix

array([[ 37.89612789,  37.89612789,  37.89612789,  37.89612789,
         37.89612789,  37.89612789,  37.89612789],
       [  2.8806166 ,   2.8806166 ,   2.8806166 ,   2.8806166 ,
          2.8806166 ,   2.8806166 ,   2.8806166 ],
       [ 82.2537587 ,  82.2537587 ,  82.2537587 ,  82.2537587 ,
         82.2537587 ,  82.2537587 ,  82.2537587 ],
       [ 17.00163631,  17.00163631,  17.00163631,  17.00163631,
         17.00163631,  17.00163631,  17.00163631],
       [142.88299314, 142.88299314, 142.88299314, 142.88299314,
        142.88299314, 142.88299314, 142.88299314]])

In [63]:
L2NormMatrix = np.array(Averaged_df.T)
L2NormMatrix = np.divide(L2NormMatrix, AveragedMatrix)
L2Norm_df = pd.DataFrame(L2NormMatrix.T)
L2Norm_df

0         1         2         3         4
0  0.505876  0.261183  0.250033  0.331474  0.316486
1  0.359902  0.312283  0.407339  0.320401  0.355255
2  0.330276  0.235575  0.353941  0.373864  0.432780
3  0.474968  0.296198  0.245499  0.320816  0.416657
4  0.386441  0.387359  0.332772  0.419130  0.387725
5  0.320947  0.417249  0.404158  0.419446  0.329186
6  0.165953  0.605715  0.558511  0.439507  0.392473

### L1 (Manhattan) Norm - Values divided by the sum of the absolute values

In [67]:
AveragedMatrix = np.array(Averaged_df)
AveragedMatrix = AveragedMatrix.T

for i in range(0, 5):
    AveragedMatrix[i] = np.sum(np.absolute(AveragedMatrix[i]))
AveragedMatrix

array([[ 96.42146667,  96.42146667,  96.42146667,  96.42146667,
         96.42146667,  96.42146667,  96.42146667],
       [  7.24636667,   7.24636667,   7.24636667,   7.24636667,
          7.24636667,   7.24636667,   7.24636667],
       [209.93229999, 209.93229999, 209.93229999, 209.93229999,
        209.93229999, 209.93229999, 209.93229999],
       [ 44.62313333,  44.62313333,  44.62313333,  44.62313333,
         44.62313333,  44.62313333,  44.62313333],
       [375.86253334, 375.86253334, 375.86253334, 375.86253334,
        375.86253334, 375.86253334, 375.86253334]])

In [68]:
L1NormMatrix = np.array(Averaged_df.T)
L1NormMatrix = np.divide(L1NormMatrix, AveragedMatrix)
L1Norm_df = pd.DataFrame(L1NormMatrix.T)
L1Norm_df

0         1         2         3         4
0  0.198822  0.103827  0.097966  0.126293  0.120311
1  0.141451  0.124140  0.159600  0.122074  0.135049
2  0.129807  0.093647  0.138678  0.142444  0.164520
3  0.186675  0.117746  0.096189  0.122233  0.158391
4  0.151881  0.153985  0.130384  0.159691  0.147392
5  0.126141  0.165867  0.158353  0.159811  0.125139
6  0.065224  0.240787  0.218831  0.167454  0.149198

### Now, Calculate weighted decision matrices for L1 and L2, each with two as instructed (w = 1, w = proportion)
### Spoiler: Part B Weighting is already done. Weights of 1 don't change anything. Onto the next weighting scheme

In [102]:
L1WeightMatrix = np.array(L1Norm_df.T)
L2WeightMatrix = np.array(L2Norm_df.T)

L1_Weights = []
L2_Weights = []

for i in range(0,5):
    L1_Weights.append(np.divide(np.sum(L1WeightMatrix[i]), (np.sum(L1WeightMatrix[0]) + np.sum(L1WeightMatrix[1])
                                                                    + np.sum(L1WeightMatrix[2]) + np.sum(L1WeightMatrix[3]) +
                                                                   np.sum(L1WeightMatrix[4]))))
L1_Weights

[0.2, 0.20000000000000004, 0.2, 0.2, 0.2]

In [103]:
for i in range(0,5):
    L2_Weights.append(np.divide(np.sum(L2WeightMatrix[i]), (np.sum(L2WeightMatrix[0]) + np.sum(L2WeightMatrix[1])
                                                                    + np.sum(L2WeightMatrix[2]) + np.sum(L2WeightMatrix[3]) +
                                                                   np.sum(L2WeightMatrix[4]))))
L2_Weights

[0.19773746957937827,
 0.19549917225722857,
 0.19835063149492516,
 0.20397616239150987,
 0.20443656427695805]

In [104]:
for i in range (0,5):
    L1WeightMatrix[i] = L1WeightMatrix[i] * L1_Weights[i]
    L2WeightMatrix[i] = L2WeightMatrix[i] * L2_Weights[i]
    
L1Weight_df = pd.DataFrame(L1WeightMatrix.T)
L2Weight_df = pd.DataFrame(L2WeightMatrix.T)
L1Weight_df

0         1         2         3         4
0  0.039764  0.020765  0.019593  0.025259  0.024062
1  0.028290  0.024828  0.031920  0.024415  0.027010
2  0.025961  0.018729  0.027736  0.028489  0.032904
3  0.037335  0.023549  0.019238  0.024447  0.031678
4  0.030376  0.030797  0.026077  0.031938  0.029478
5  0.025228  0.033173  0.031671  0.031962  0.025028
6  0.013045  0.048157  0.043766  0.033491  0.029840

In [105]:
L2Weight_df

0         1         2         3         4
0  0.100031  0.051061  0.049594  0.067613  0.064701
1  0.071166  0.061051  0.080796  0.065354  0.072627
2  0.065308  0.046055  0.070204  0.076259  0.088476
3  0.093919  0.057906  0.048695  0.065439  0.085180
4  0.076414  0.075728  0.066006  0.085493  0.079265
5  0.063463  0.081572  0.080165  0.085557  0.067298
6  0.032815  0.118417  0.110781  0.089649  0.080236

## Now we compute ideal/negative-ideal row vectors, then compute the Euclidian and Manhattan distances from each real row, to them.

In [144]:
#I'm assuming a greater value is always worse, since these are pollutants (so the Ideal row takes the Minimimums)
L2_IDR = []
L2_NIDR = []
L1_IDR = []
L1_NIDR = []

for i in range(0,5):
    L1_IDR.append(L1Weight_df[i].min())
    L1_NIDR.append(L1Weight_df[i].max())
    L2_IDR.append(L2Weight_df[i].min())
    L2_NIDR.append(L2Weight_df[i].max())

In [145]:
L2_IDR

[0.03281507700419608,
 0.04605463230032567,
 0.0486948442851455,
 0.06535407110045431,
 0.06470126235231155]

In [160]:
L1_distancesIDR = []
L1_distancesNIDR = []
L2_distancesIDR = []
L2_distancesNIDR = []

for i in range(0,7):
    L1RowVector = np.array(L1Weight_df.loc[i])
    L1_distancesIDR.append(np.sum(np.absolute(L1RowVector - L1_IDR)))
    L1_distancesNIDR.append(np.sum(np.absolute(L1RowVector - L1_NIDR)))
    L2RowVector = np.array(L2Weight_df.loc[i])
    L2_distancesIDR.append(np.sqrt(np.sum(np.square(L2RowVector - L2_IDR))))
    L2_distancesNIDR.append(np.sqrt(np.sum(np.square(L2RowVector - L2_NIDR))))

In [161]:
L1_Metric = np.array(np.divide(L1_distancesIDR, (np.array(L1_distancesIDR) + np.array(L1_distancesNIDR))))
L2_Metric = np.array(np.divide(L2_distancesIDR, (np.array(L2_distancesIDR) + np.array(L2_distancesNIDR))))
L1_Metric

array([0.30381983, 0.37501182, 0.34819763, 0.37281905, 0.4987897 ,
       0.48251722, 0.69791037])

In [159]:
L2_Metric

array([0.41114036, 0.40814955, 0.34043507, 0.42055698, 0.47586818,
       0.48404019, 0.59529992])

## And again, with the unweighted versions

In [166]:
L2_IDR_UW = []
L2_NIDR_UW = []
L1_IDR_UW = []
L1_NIDR_UW = []

for i in range(0,5):
    L1_IDR_UW.append(L1Norm_df[i].min())
    L1_NIDR_UW.append(L1Norm_df[i].max())
    L2_IDR_UW.append(L2Norm_df[i].min())
    L2_NIDR_UW.append(L2Norm_df[i].max())

L1_distancesIDR_UW = []
L1_distancesNIDR_UW = []
L2_distancesIDR_UW = []
L2_distancesNIDR_UW = []

for i in range(0,7):
    L1RowVector_UW = np.array(L1Norm_df.loc[i])
    L1_distancesIDR_UW.append(np.sum(np.absolute(L1RowVector_UW - L1_IDR_UW)))
    L1_distancesNIDR_UW.append(np.sum(np.absolute(L1RowVector_UW - L1_NIDR_UW)))
    L2RowVector_UW = np.array(L2Norm_df.loc[i])
    L2_distancesIDR_UW.append(np.sqrt(np.sum(np.square(L2RowVector_UW - L2_IDR_UW))))
    L2_distancesNIDR_UW.append(np.sqrt(np.sum(np.square(L2RowVector_UW - L2_NIDR_UW))))
    
L1_Metric_UW = np.array(np.divide(L1_distancesIDR_UW, (np.array(L1_distancesIDR_UW) + np.array(L1_distancesNIDR_UW))))
L2_Metric_UW = np.array(np.divide(L2_distancesIDR_UW, (np.array(L2_distancesIDR_UW) + np.array(L2_distancesNIDR_UW))))

In [167]:
L1_Metric_UW

array([0.30381983, 0.37501182, 0.34819763, 0.37281905, 0.4987897 ,
       0.48251722, 0.69791037])

In [168]:
L2_Metric_UW

array([0.41094416, 0.4075427 , 0.33670701, 0.41951403, 0.4745634 ,
       0.48410356, 0.59596809])

## Now, doing the TOPSIS method on a "Rank Matrix", where simple ranks are pre-generated for each criteria. (computed in google sheets, and imported via CSV)

In [183]:
RankMatrix_df = pd.read_csv('RankMatrix.csv', header=None)
RankMatrix = RankMatrix_df.astype(float)
RankMatrix

0    1    2    3    4
0  1.0  6.0  6.0  5.0  7.0
1  4.0  4.0  2.0  7.0  5.0
2  5.0  7.0  4.0  4.0  1.0
3  2.0  5.0  7.0  6.0  2.0
4  3.0  3.0  5.0  3.0  4.0
5  6.0  2.0  3.0  2.0  6.0
6  7.0  1.0  1.0  1.0  3.0

## L2

In [185]:
RankMatrix = np.array(RankMatrix_df)
RankMatrix = RankMatrix.T

for i in range(0, 5):
    RankMatrix[i] = np.sqrt(np.sum(np.square((RankMatrix[i]))))
RankMatrix

array([[11, 11, 11, 11, 11, 11, 11],
       [11, 11, 11, 11, 11, 11, 11],
       [11, 11, 11, 11, 11, 11, 11],
       [11, 11, 11, 11, 11, 11, 11],
       [11, 11, 11, 11, 11, 11, 11]], dtype=int64)

In [186]:
L2NormRank = np.array(RankMatrix_df.T)
L2NormRank = np.divide(L2NormRank, RankMatrix)
L2NormRank_df = pd.DataFrame(L2NormRank.T)
L2NormRank_df

0         1         2         3         4
0  0.090909  0.545455  0.545455  0.454545  0.636364
1  0.363636  0.363636  0.181818  0.636364  0.454545
2  0.454545  0.636364  0.363636  0.363636  0.090909
3  0.181818  0.454545  0.636364  0.545455  0.181818
4  0.272727  0.272727  0.454545  0.272727  0.363636
5  0.545455  0.181818  0.272727  0.181818  0.545455
6  0.636364  0.090909  0.090909  0.090909  0.272727

## L1

In [187]:
RankMatrix = np.array(RankMatrix_df)
RankMatrix = RankMatrix.T

for i in range(0, 5):
    RankMatrix[i] = np.sum(np.absolute(RankMatrix[i]))
RankMatrix

L1NormRankMatrix = np.array(RankMatrix_df.T)
L1NormRankMatrix = np.divide(L1NormRankMatrix, RankMatrix)
L1NormRank_df = pd.DataFrame(L1NormRankMatrix.T)
L1NormRank_df

0         1         2         3         4
0  0.035714  0.214286  0.214286  0.178571  0.250000
1  0.142857  0.142857  0.071429  0.250000  0.178571
2  0.178571  0.250000  0.142857  0.142857  0.035714
3  0.071429  0.178571  0.250000  0.214286  0.071429
4  0.107143  0.107143  0.178571  0.107143  0.142857
5  0.214286  0.071429  0.107143  0.071429  0.214286
6  0.250000  0.035714  0.035714  0.035714  0.107143

## Rank Matrix TOPSIS-MCDM time

In [188]:
L2_IDR_Rank = []
L2_NIDR_Rank = []
L1_IDR_Rank = []
L1_NIDR_Rank = []

for i in range(0,5):
    L1_IDR_Rank.append(L1NormRank_df[i].min())
    L1_NIDR_Rank.append(L1NormRank_df[i].max())
    L2_IDR_Rank.append(L2NormRank_df[i].min())
    L2_NIDR_Rank.append(L2NormRank_df[i].max())

L1_distancesIDR_Rank = []
L1_distancesNIDR_Rank = []
L2_distancesIDR_Rank = []
L2_distancesNIDR_Rank = []

for i in range(0,7):
    L1RowVector_Rank = np.array(L1NormRank_df.loc[i])
    L1_distancesIDR_Rank.append(np.sum(np.absolute(L1RowVector_Rank - L1_IDR_Rank)))
    L1_distancesNIDR_Rank.append(np.sum(np.absolute(L1RowVector_Rank - L1_NIDR_Rank)))
    L2RowVector_Rank = np.array(L2NormRank_df.loc[i])
    L2_distancesIDR_Rank.append(np.sqrt(np.sum(np.square(L2RowVector_Rank - L2_IDR_Rank))))
    L2_distancesNIDR_Rank.append(np.sqrt(np.sum(np.square(L2RowVector_Rank - L2_NIDR_Rank))))
    
L1_Metric_Rank = np.array(np.divide(L1_distancesIDR_Rank, (np.array(L1_distancesIDR_Rank) + np.array(L1_distancesNIDR_Rank))))
L2_Metric_Rank = np.array(np.divide(L2_distancesIDR_Rank, (np.array(L2_distancesIDR_Rank) + np.array(L2_distancesNIDR_Rank))))

In [189]:
L1_Metric_Rank

array([0.66666667, 0.56666667, 0.53333333, 0.56666667, 0.43333333,
       0.46666667, 0.26666667])

In [190]:
L2_Metric_Rank

array([0.60912879, 0.55138448, 0.52348923, 0.54514108, 0.43782892,
       0.47574954, 0.36222937])

In [203]:
L2NormRank_df['Metric'] = L2_Metric_Rank
L2NormRank_df = L2NormRank_df.drop(['Ranks'], axis=1)
L2NormRank_df

0         1         2         3         4    Metric
0  0.090909  0.545455  0.545455  0.454545  0.636364  0.609129
1  0.363636  0.363636  0.181818  0.636364  0.454545  0.551384
2  0.454545  0.636364  0.363636  0.363636  0.090909  0.523489
3  0.181818  0.454545  0.636364  0.545455  0.181818  0.545141
4  0.272727  0.272727  0.454545  0.272727  0.363636  0.437829
5  0.545455  0.181818  0.272727  0.181818  0.545455  0.475750
6  0.636364  0.090909  0.090909  0.090909  0.272727  0.362229

In [204]:
L1NormRank_df['Metric'] = L1_Metric_Rank
L1NormRank_df

0         1         2         3         4    Metric
0  0.035714  0.214286  0.214286  0.178571  0.250000  0.666667
1  0.142857  0.142857  0.071429  0.250000  0.178571  0.566667
2  0.178571  0.250000  0.142857  0.142857  0.035714  0.533333
3  0.071429  0.178571  0.250000  0.214286  0.071429  0.566667
4  0.107143  0.107143  0.178571  0.107143  0.142857  0.433333
5  0.214286  0.071429  0.107143  0.071429  0.214286  0.466667
6  0.250000  0.035714  0.035714  0.035714  0.107143  0.266667

In [207]:
L2Norm_df['Metric'] = L2_Metric_UW
L2Norm_df['Disatance-IDR'] = L2_distancesIDR_UW
L2Norm_df['Disatance-NIDR'] = L2_distancesNIDR_UW
L2Norm_df

0         1         2         3         4    Metric  Disatance-IDR  \
0  0.505876  0.261183  0.250033  0.331474  0.316486  0.410944       0.341096   
1  0.359902  0.312283  0.407339  0.320401  0.355255  0.407543       0.266825   
2  0.330276  0.235575  0.353941  0.373864  0.432780  0.336707       0.234828   
3  0.474968  0.296198  0.245499  0.320816  0.416657  0.419514       0.330454   
4  0.386441  0.387359  0.332772  0.419130  0.387725  0.474563       0.306745   
5  0.320947  0.417249  0.404158  0.419446  0.329186  0.484104       0.303600   
6  0.165953  0.605715  0.558511  0.439507  0.392473  0.595968       0.504917   

   Disatance-NIDR  
0        0.488934  
1        0.387892  
2        0.462598  
3        0.457253  
4        0.339628  
5        0.323538  
6        0.342304

In [208]:
L1Norm_df['Metric'] = L1_Metric_UW
L1Norm_df['Disatance-IDR'] = L1_distancesIDR_UW
L1Norm_df['Disatance-NIDR'] = L1_distancesNIDR_UW
L1Norm_df

0         1         2         3         4    Metric  Disatance-IDR  \
0  0.198822  0.103827  0.097966  0.126293  0.120311  0.303820       0.149774   
1  0.141451  0.124140  0.159600  0.122074  0.135049  0.375012       0.184869   
2  0.129807  0.093647  0.138678  0.142444  0.164520  0.348198       0.171651   
3  0.186675  0.117746  0.096189  0.122233  0.158391  0.372819       0.183788   
4  0.151881  0.153985  0.130384  0.159691  0.147392  0.498790       0.245888   
5  0.126141  0.165867  0.158353  0.159811  0.125139  0.482517       0.237866   
6  0.065224  0.240787  0.218831  0.167454  0.149198  0.697910       0.344048   

   Disatance-NIDR  
0        0.343195  
1        0.308100  
2        0.321319  
3        0.309181  
4        0.247081  
5        0.255103  
6        0.148921

In [209]:
L1Weight_df['Metric'] = L1_Metric
L1Weight_df['Disatance-IDR'] = L1_distancesIDR
L1Weight_df['Disatance-NIDR'] = L1_distancesNIDR
L1Weight_df

0         1         2         3         4    Metric  Disatance-IDR  \
0  0.039764  0.020765  0.019593  0.025259  0.024062  0.303820       0.029955   
1  0.028290  0.024828  0.031920  0.024415  0.027010  0.375012       0.036974   
2  0.025961  0.018729  0.027736  0.028489  0.032904  0.348198       0.034330   
3  0.037335  0.023549  0.019238  0.024447  0.031678  0.372819       0.036758   
4  0.030376  0.030797  0.026077  0.031938  0.029478  0.498790       0.049178   
5  0.025228  0.033173  0.031671  0.031962  0.025028  0.482517       0.047573   
6  0.013045  0.048157  0.043766  0.033491  0.029840  0.697910       0.068810   

   Disatance-NIDR  
0        0.068639  
1        0.061620  
2        0.064264  
3        0.061836  
4        0.049416  
5        0.051021  
6        0.029784

In [210]:
L2Weight_df['Metric'] = L2_Metric
L2Weight_df['Disatance-IDR'] = L2_distancesIDR
L2Weight_df['Disatance-NIDR'] = L2_distancesNIDR
L2Weight_df

0         1         2         3         4    Metric  Disatance-IDR  \
0  0.100031  0.051061  0.049594  0.067613  0.064701  0.411140       0.067446   
1  0.071166  0.061051  0.080796  0.065354  0.072627  0.408150       0.052811   
2  0.065308  0.046055  0.070204  0.076259  0.088476  0.340435       0.046932   
3  0.093919  0.057906  0.048695  0.065439  0.085180  0.420557       0.065525   
4  0.076414  0.075728  0.066006  0.085493  0.079265  0.475868       0.060817   
5  0.063463  0.081572  0.080165  0.085557  0.067298  0.484040       0.060050   
6  0.032815  0.118417  0.110781  0.089649  0.080236  0.595300       0.099612   

   Disatance-NIDR  
0        0.096599  
1        0.076580  
2        0.090927  
3        0.090280  
4        0.066985  
5        0.064010  
6        0.067719

In [211]:
L1NormRank_df.to_csv('Pre-RankedMCDM-L1.csv')
L2NormRank_df.to_csv('Pre-RankedMCDM-L2.csv')

L2Norm_df.to_csv('UnweightedMCDM-L2.csv')
L1Norm_df.to_csv('UnweightedMCDM-L1.csv')

L1Weight_df.to_csv('WeightedMCDM-L1.csv')
L2Weight_df.to_csv('WeightedMCDM-L2.csv')


## Now back into Google sheets for the final rankings based on the obtained metric 